### PR TITLE
Initial code stub

### PR DESCRIPTION
**Pull request by codecurve**
Just so that there is something for BuildBot to build.

### CODE REVIEW

**Comment by nickerso** [comment]
I don't think we should be pulling any code into the repository until such time as the coding standard is agreed upon. If the coding standard is based on this code, then there are some problems. It would also be good, Randall, if you could try to tidy up the history in your branches so that we don't need to be pulling all these dummy commits/comments into the repository.

**Comment by agarny** [comment]
+1 with regards to the coding standard (and the git history in fact).

**Comment by hsorby** [comment]
I would also like to add that the testing should be done using gtest, even for this simple case.  This stub should be the seed of how future development is to take place thus following the proper process as described.

**Comment by agarny** [comment]
+1 wrt gtest.

**Pull request closed without merging**
