### PR TITLE
Starter object model and libCellML intro

### PR DESCRIPTION
**Pull request by codecurve**

### CODE REVIEW

**Comment by nickerso** [comment]
Hi Randall. Just a couple of initial comments.
- The .project file should not be added to the repository (you can create a .gitignore to hide it from git if you'd like).
- In my opinion, the source UML files (model.di, model.notation, model.uml) should be in a separate repository. We have the generated images in with the docs, which is what people want to see. No need to duplicate the information in the libCellML repository.
- I'm not sure it is worth pulling this in yet since the discussion is just getting started over on your fork/branch of the repository. It is probably worth waiting until a "closer to final" version is ready and then we can merge that in and centralise any final tweaks. I'm worried that duplicating the content here at this time will fragment the discussion and lead to increased workload in collating it all together.

What do others think about this?

Cheers,
Andre.

**Comment by jonc125** [comment]
I'd agree about not merging it yet. Although note that it's common GitHub style to leave a pull request open while a piece of work is ongoing, as a convenient place to summarise discussion on that work item. Any new commits to the source branch get added to the pull request automatically.

**Comment by nickerso** [comment]
good point, thanks!

**Comment by agarny** [comment]
FWIW, I agree with both David's and Jonathan's comments.

**Comment by codecurve** [comment]
From what I can tell, it is preferable to include the .project, although I don't think we want it at the top level in the long run, but for the sake of not having to figure out sub-repos or having the eclipse project not at the top level, I committed it now, since we can always figure that out later.

Since the images are derived from the UML files, the docs generator could (in theory anyway) generate the images from the UML files (perhaps there is a Papyrus CLI, or some other UML CLI image generator).  Anyway, it probably makes more sense to version control the UML files than the image files, but for the sake of expedience, I just did it this way for now.

Jonathan's understanding of the use of a pull request is exactly the same as mine, i.e. discuss the work that is on the branch for the pull request and make changes on the branch until eventually the pull request gets merged.

**Comment by hsorby** [comment]
It is definitely not preferable to include the .project file in the repository it may contain absolute paths that are only relevant to a particular user so they should not be present in the repository.

The source UML files should also not be added to the repository as they are for generating the images of the object model design.  They are not in themselves of interest to libCellML, I agree with 
Andre in that they should be placed in another repository for managing.

**Comment by codecurve** [comment]
I don't really mind whether or not we include the .project and UML files, but I don't see any harm in including them now and moving them out later.

**Comment by nickerso** [comment]
Given one vote of ambivalence and three votes to remove those files from this repository, they should be removed. 

Might even be worth creating a new branch with just the near-complete version of the objectModel document just to make the history of the cellml/libcellml repo cleaner - but we can decide that later in the review/discussion process.

**Comment by codecurve** [comment]
OK, see https://github.com/cellml/libcellml/pull/9

So we should probably close this pull request?

**Comment by nickerso** [comment]
Thanks Randall. Closing this one in favour of #9.

**Pull request closed without merging**
