### PR TITLE
Various cleaning ups.

### PR DESCRIPTION
**Pull request by agarny**

### CODE REVIEW

**Comment by nickerso** [comment]
I'm happy for this to be merged in, with or without the change to the make.bat being explained.

**Comment by nickerso** [comment]
I'm now very happy for this to be merged in.

**Comment by mirams** [comment]
Github is saying there are conflicts, please feel free to merge Alan, as you are probably best placed to sort them out!

**Comment by agarny** [comment]
Yes, that was because another pull request had been accepted in between. Anyway, it should all be fine now. This being said, in the future, we probably ought to make sure that there is only ever one pull request waiting to be accepted/rejected. This would avoid the situation we just faced.

**Comment by nickerso** [comment]
I don't see anything wrong with having multiple pull requests open, its the way git/github is designed to work in a collaborative environment. I imagine this will be something covered in the libcellml development process/workflow document.

**Comment by agarny** [comment]
Well, between clicking a button that does everything for you (via the GitHub website) and having to do things from the command line (incl. sorting out the conflicts), I think my preference goes to the former... :) In other words, our time could be better used elsewhere if we could stick to some simple rules.

**Comment by jonc125** [comment]
Most of the time, especially as the project grows, you won't have conflicting pull requests. But it's certainly a good idea to merge new pull requests as soon as possible! It would also be sensible for people creating pull requests to check whether there are any existing ones that are likely to conflict.

**Pull request merged**
