### PR TITLE
Just gtest.

### PR DESCRIPTION
**Pull request by codecurve**
Originally was pull request cellml/libcellml#26, but due to not being able to change the target branch of a pull request, had to close and restart (since original erroneously targeted master).
The focus here is on getting Google Test into the repo, so that it does not clutter future pull requests which focus on actual use cases.

### CODE REVIEW

**Comment by codecurve** [comment]
Just to be clear: review comments on cellml/libcellml#26 still apply to this pull request, but please continue any further discussion on this pull request.

**Comment by codecurve** [comment]
Review progress

Done (or otherwise addressed):
- This pull request should be made against the develop branch of cellml/libcellml
- src file names should be all lowercase
- header guards missing from LibcellmlConfig.h.in
- version number variables should be all uppercase (Libcellml_VERSION_MAJOR)
- version test doesn’t test anything
- #include should be the first include in Version.cpp
- patch version missing from version number

The following are not done yet.  I'd propose we add all but the first one of these as a separate issue ("cmake improvements"), and defer it till later, so that we can focus on domain specific issues for now.
- api header files put into libcellml directory so that  all api includes are the same for internal calls (please clarify what is meant here)
- refactor CMakeLists.txt layout put CMakeLists.txt in src directory for the library target put CMakeLists.txt in tests  directory for the test targets, leaving the main CMakeLists.txt for handling general options, tests, build type etc.
- not able to set type of library to build [shared, static]
- library target should be named cellml, not add_library(Libcellml
- test option should be LIBCELLML_TESTS with a test for TESTS variable, all configurable options should be namespaced with LIBCELLML_ for gui users
- can’t set -g -Wall to CMAKE_CXX_FLAGS this is not generic to all compilers
- check for cmake c++ compiler support is not well thought through, if there is a problem with the compiler it should be an error

**Comment by nickerso** [comment]
I don't think it is acceptable to delay addressing outstanding issues in the review. They all seem like either critical issues to address in the proposed code or trivial changes that should be quick to fix.

**Comment by nickerso** [comment]
Further review comment: I'd expect the documentation of the getVersion() method to include a description of the returned string.

**Comment by hsorby** [comment]
Clarification: in the src directory create a directory "libcellml" into which you put API header files

**Comment by nickerso** [comment]
Further to @hsorby's comment regarding "-g" in the CXX flags, it is bad to force debug build (and even worse to do so in a manner that will not work across all target compiler toolchains) - should make use of standard CMake build types (Debug, Release, etc) which will take care of such flags in a way that is safe across compiler toolchains.

**Comment by codecurve** [comment]
"check for cmake c++ compiler support is not well thought through, if there is a problem with the compiler it should be an error" is resolved if we use cmake 3.2 (currently at rc2 stage). See https://github.com/cellml/libcellml/blob/ab70fbb3798597fde0c23cad39c5df16df0cfefc/CMakeLists.txt

**Comment by hsorby** [comment]
I would probably use this form for setting a targets properties:

set_target_properties(libcellmlTest PROPERTIES CXX_STANDARD 11 CXX_STANDARD_REQUIRED ON)

I would prefer to stick with CMake 3.1 if possible.  As demonstrated the above  works on my GNU/Linux with CMake 3.1

**Comment by codecurve** [comment]
BuildBot tests currently failing on Windows and Mac slaves, passing on Linux.  The fix is to use CMake 3.2.  Once CMake 3.2 is released (should be soon, since it is at release candidate 2 at the time of writing this), we will install it on the build slaves, and update the minimum version requirement to 3.2.  Leaving minimum version requirement at 3.1 for now so that it still builds on Linux.  See http://www.cmake.org/Bug/view.php?id=15355

This was discussed with @hsorby a few minutes ago.

**Comment by hsorby** [comment]
- the test for the version should test the expected value vs. the actual value, not actual vs. actual
- still have the tests option, this should be removed
- LIBCELLML_TESTS variable should default to ON
- should be able to set build type similarly to how tests is set

**Comment by nickerso** [comment]
That

> Merge branch 'upstream_master' into gtest01

should not be here.

**Comment by nickerso** [comment]
With the mix up in merging #33 and reverting (#35) and its subsequent merge into this pull request, I wonder if it might not be significantly less hassle to simply start this one over? Is cherry picking 7ea7aab and starting from there an option? That seems to be the one with everything in a state which is working and presumably answering most issues that have arisen in this review...

**Comment by agarny** [comment]
I haven't followed things very closely, but it certainly looks like a mess... :)

**Pull request closed without merging**
