### PR TITLE
Roll back to just plain gtest.

### PR DESCRIPTION
**Pull request by codecurve**
Google test setup for cellml/libcellml#25

### CODE REVIEW

**Comment by hsorby** [comment]
My thoughts (in no particular order):
- This pull request should be made against the develop branch of cellml/libcellml
- src file names should be all lowercase
- api header files put into libcellml directory so that all api includes are the same for internal calls
- #include <Versioin.h> should be the first include in Version.cpp
- header gaurds missing from LibcellmlConfig.h.in
- patch version missing from version number
- refactor CMakeLists.txt layout put CMakeLists.txt in src directory for the library target put CMakeLists.txt in tests  directory for the test targets, leaving the main CMakeLists.txt for handling general options, tests, build type etc.
- not able to set type of library to build [shared, static]
- library target should be named cellml, not add_library(Libcellml
- version number variables should be all uppercase (Libcellml_VERSION_MAJOR)
- test option should be LIBCELLML_TESTS with a test for TESTS variable, all configurable options should be namespaced with LIBCELLML_ for gui users
- can’t set -g -Wall to CMAKE_CXX_FLAGS this is not generic to all compilers
- check for cmake c++ compiler support is not well thought through, if there is a problem with the compiler it should be an error
- version test doesn’t test anything

**Comment by nickerso** [comment]
I agree with Hugh's comments. And would add that the actual commit message is not particularly useful or informative. It would be good to see more informative commit messages being used in future (I'm guessing this particular one is a consequence of where the code originated).

**Comment by codecurve** [comment]
The target of a pull request can't be changed (isaacs/github/issues/18). 
I'll close this and make the pull request again to the correct branch. My bad, sorry.

**Comment by codecurve** [comment]
The replacement pull request is cellml/libcellml#28

**Pull request closed without merging**
