### PR TITLE
Add a usecase document

### PR DESCRIPTION
**Pull request by hsorby**

### CODE REVIEW

**Comment by nickerso** [comment]
Thanks for this Hugh. It looks good to me.

**Comment by agarny** [comment]
Agreed, this looks like a good starting point to me too. Merging.

**Comment by nickerso** [comment]
looks like Alan closed without merging, so I'm reopening.

**Comment by agarny** [comment]
Sorry, I merged it first, but then I wanted to comment, so I commented and closed, which apparently cancelled my merge. My bad!

**Pull request merged**
