### PR TITLE
Preliminary design, doc files only

### PR DESCRIPTION
**Pull request by codecurve**
Same as uml01 branch, but with only files under docs retained.

### CODE REVIEW

**Comment by nickerso** [comment]
What is the status of this pull request? I suggest closing it as at the very least it will need to be redone against the develop branch.

**Comment by codecurve** [comment]
Yeah, it's now a stale branch. I'd suggest merging it, but using git on your local system to merge with prime's develop branch.  I tried to see what a merge with prime/develop would be like, and it's fairly tame, trivial conflict to resolve.  However, it won't look pretty on GitHub, the diff will blow-up, similar to what happened a while ago, also with a pull request that had gone stale.

**Comment by nickerso** [comment]
I'm not sure I understand, why would a stale branch be merged in? I recall some outstanding issues in the discussion of the proposed design over on the cellml-tools-developers list, so I don't think this can be merged in anyway.

**Comment by nickerso** [comment]
OK, so I'll close this for now. We can reopen it as a pull request against the develop branch if required.

**Pull request closed without merging**
