### PR TITLE
Basic model use case01

### PR DESCRIPTION
**Pull request by codecurve**
This code satisfies more than is required for issue cellml/libcellml#21. But, as commented on that issue, a recent decision was made to roll back the code so that reviewers can be involved earlier, since they prefer to not have to catch up. The reason for proceeding with this pull request is to demonstrate the process: creating the pull request request that corresponds to the issue, which will trigger the automated build/test infrastructure, etc.

### CODE REVIEW

**Comment by agarny** [comment]
Commenting here since issue #21 is now closed.

Regarding CellML identifiers, it would still be good to use valid ones in tests. Many people (myself included) rely on tests (among other things) to learn about the use of an API, etc. So, to put 'invalid' code isn't good practice in my opinion.

As for using the `using` directive, I would just like to refer to the [Google C++ Style Guide](http://google-styleguide.googlecode.com/svn/trunk/cppguide.html) and the [namespaces section](http://google-styleguide.googlecode.com/svn/trunk/cppguide.html#Namespaces) in particular.

**Comment by agarny** [comment]
Regarding this pull request itself:
- For me, it is ridiculously big, so by default I couldn't be bothered to check it out in details.
- It includes, among other things, both `gtest` (including its samples and tests!) and `xsd`. Surely, those could and should have been put in a pull request of their own?
- If I click on the `Files changed` tab above, GitHub tells me that there are too many changes, hence I can't see everything that has 'changed'.
- Etc.

**Comment by nickerso** [comment]
Hi Alan, the purpose of this pull request was simply to demonstrate that the connection between the buildbot and github is now working - as shown by the red crosses and the final green tick with the actual commits listed above and the final green tick "all is well". The actual code is irrelevant in this instance and I'll now close this pull request. As the development process document gets written, it will spell out how this process works.

**Comment by agarny** [comment]
OK, I was a bit confused by the latest commits in this pull request, but now it makes sense. Thanks.

**Comment by codecurve** [comment]
@agarny How this would be reviewed if it ever were to be reviewed:
- Diff gtest sources with originals from gtest site - no differences would be found.
- Run XSD on the schema file, diff/compare to generated code in pull request - no differences would be found.
- Remaining code to be reviewed would probably take between half an hour and 2 hours to review.

This is different from the usual process, because it includes the generated code and gtest, future commits would not include those usually.

**Pull request closed without merging**
