### PR TITLE
CodeSynthesis XSD library (take 2)

### PR DESCRIPTION
**Pull request by codecurve**
Just the library code for CodeSynthesis XSD, no additional code.
This is currently off the head of the gtest01 branch, changes on that branch can be merged into this pull request.

This is a subtask of #31

It is not expected that the code itself will be reviewed. This code is unused at the moment, but has been isolated so that the next pull request towards this use case is not cluttered with so much additional code, which will hopefully make it easier to review that pull request.

This was originally #32, but @dnickerso requested this be done from the current master (since #28 has not been merged yet).

### CODE REVIEW

**Comment by nickerso** [comment]
#34 is for the actual discussion on the use of this approach in libCellML. This is not a subtask of #31.

This code will not pass the tests as it stands, but that is probably ok for the purpose of this pull request. As Randall (@codecurve) points out above, this pull request is just to get the libxsd code into the repository as an external dependency without confusing things with the merging of actual libcellml developments.

**Comment by nickerso** [comment]
As above, the code doesn't need review and hasn't been reviewed, but I believe this pull request can be merged in.

**Comment by codecurve** [comment]
Doh! We all missed that, I think it was meant to be a pull/merge to develop, not master.

**Comment by nickerso** [comment]
OK, I have reverted the merge. Please resubmit the pull request against the develop branch.

**Pull request merged**
